using AI_Dashboard.Application.Common.Interfaces;
using AI_Dashboard.Domain.Entities;
using MediatR;

namespace AI_Dashboard.Application.Widgets.Commands;

// Creates a brand-new widget row (own Id) that is a copy of an existing one
// on the SAME dashboard, plus a copy of its query row (same SQL, same
// PromptId for traceability - it's still "generated by" that original
// prompt, just duplicated by the user afterwards). The copy is offset
// directly below the source so it doesn't render on top of it before the
// user drags it somewhere else, and the dashboard's DefinitionJson layout
// is updated in the same way DeleteWidget keeps it in sync.
public record DuplicateWidgetCommand(short TenantId, int UserId, int SourceWidgetId) : IRequest<Widget>;

public class DuplicateWidgetCommandHandler : IRequestHandler<DuplicateWidgetCommand, Widget>
{
    private readonly IWidgetRepository _widgetRepo;
    private readonly IQueryRepository _queryRepo;
    private readonly IDashboardRepository _dashboardRepo;

    public DuplicateWidgetCommandHandler(
        IWidgetRepository widgetRepo,
        IQueryRepository queryRepo,
        IDashboardRepository dashboardRepo)
    {
        _widgetRepo = widgetRepo;
        _queryRepo = queryRepo;
        _dashboardRepo = dashboardRepo;
    }

    public async Task<Widget> Handle(DuplicateWidgetCommand request, CancellationToken ct)
    {
        var source = await _widgetRepo.GetByIdAsync(request.TenantId, request.SourceWidgetId, ct)
            ?? throw new KeyNotFoundException($"Widget {request.SourceWidgetId} not found.");

        if (source.Dashboard.UserId != request.UserId)
            throw new UnauthorizedAccessException("You do not have access to this widget.");

        var copy = new Widget
        {
            TenantId = request.TenantId,
            DashboardId = source.DashboardId,
            Title = $"{source.Title} (Copy)",
            WidgetType = source.WidgetType,
            Width = source.Width,
            Height = source.Height,
            PositionX = source.PositionX,
            PositionY = (short)(source.PositionY + source.Height),
            RefreshInterval = source.RefreshInterval,
            DataSource = source.DataSource,
            ConfigJson = source.ConfigJson,
            CreatedBy = request.UserId
        };
        await _widgetRepo.AddAsync(copy, ct);

        var sourceQuery = await _queryRepo.GetByWidgetIdAsync(request.TenantId, request.SourceWidgetId, ct);
        if (sourceQuery is not null)
        {
            var newQuery = await _queryRepo.AddAsync(new Query
            {
                TenantId = request.TenantId,
                DashboardId = source.DashboardId,
                WidgetId = copy.Id,
                PromptId = sourceQuery.PromptId,
                SqlQuery = sourceQuery.SqlQuery,
                CreatedBy = request.UserId
            }, ct);

            // Not reloaded from the DB - just attached in-memory so callers
            // (the controller) can read copy.Queries.FirstOrDefault()?.SqlQuery
            // straight off the returned object without an extra round-trip.
            copy.Queries.Add(newQuery);
        }

        await AddWidgetToLayoutAsync(request.TenantId, source.DashboardId, copy, ct);

        return copy;
    }

    private async Task AddWidgetToLayoutAsync(short tenantId, int dashboardId, Widget copy, CancellationToken ct)
    {
        var dashboard = await _dashboardRepo.GetByIdAsync(tenantId, dashboardId, ct);
        if (dashboard is null) return;

        try
        {
            using var existing = System.Text.Json.JsonDocument.Parse(dashboard.DefinitionJson);
            var style = existing.RootElement.TryGetProperty("style", out var s) ? s.GetString() : null;
            var gridCols = existing.RootElement.TryGetProperty("gridCols", out var g) ? g.GetInt32() : 12;

            var widgets = new List<object>();
            if (existing.RootElement.TryGetProperty("widgets", out var arr))
            {
                widgets.AddRange(arr.EnumerateArray().Select(w => (object)new
                {
                    id = w.GetProperty("id").GetInt32(),
                    type = w.GetProperty("type").GetString(),
                    x = w.GetProperty("x").GetInt16(),
                    y = w.GetProperty("y").GetInt16(),
                    w = w.GetProperty("w").GetInt16(),
                    h = w.GetProperty("h").GetInt16()
                }));
            }

            widgets.Add(new
            {
                id = copy.Id,
                type = copy.WidgetType,
                x = copy.PositionX,
                y = copy.PositionY,
                w = copy.Width,
                h = copy.Height
            });

            dashboard.DefinitionJson = System.Text.Json.JsonSerializer.Serialize(new
            {
                style,
                gridCols,
                widgets
            });
            await _dashboardRepo.UpdateAsync(dashboard, ct);
        }
        catch
        {
            // Malformed/legacy layout JSON - not worth failing the duplicate over.
            // The widgets table row is still the source of truth on next full load.
        }
    }
}